# test/parser.py
# vim:ts=4:sw=4:noexpandtab

import sys

from os import remove
from tempfile import mkstemp
from unittest import TestCase, main

if '..' not in sys.path:
	sys.path.append('..')

from localrepo.parser import PkgbuildParser, PkginfoParser, DescParser, ParserError


class ParserTest(TestCase):

	PKGBUILD = '''# Maintainer: ushi <ushi@porkbox.net>
hello=huiii
pkgname=local-repo
pkgver=
pkgrel=1
pkgdesc="Local repository manager"
arch=('any')
url="http://ushi.wurstcase.net/local-repo/"
license=('GPL')
depends=('tar' 'pacman' 'python' "$hello")
makedepends=('gettext')
install=local-repo.install
source=("https://github.com/downloads/ushis/local-repo/local-repo-${pkgver}.tar.gz")
md5sums=('ea613c8ffb3993ffdde804307ecc08e4')

package() {
	cd "${srcdir}/${pkgname}"
	python setup.py install --prefix="${pkgdir}/usr"
	install -D -m644 bash-completion "${pkgdir}/usr/share/bash-completion/completions/local-repo"
	install -D -m644 share/config.example "${pkgdir}/usr/share/local-repo/config.example"
}
'''
	VERSION = '''
pkgver=1.6.2'''

	PKGINFO = '''# Generated by makepkg 4.0.2
# using fakeroot version 1.18.2
# Mon Mar 26 02:02:31 UTC 2012
pkgname = local-repo
pkgver = 1.6.2-1
pkgdesc = Local repository manager
url = https://github.com/ushis/local-repo
builddate = 1332727351
size = 303104
arch = any
license = GPL
depend = tar
depend = pacman
depend = python'''

	PACK ='''
packager = ushi <martin.kalcher@gmail.com>
'''

	DESC = '''%FILENAME%
local-repo-1.6.2-1-any.pkg.tar.xz

%VERSION%
1.6.2-1

%DESC%
Local repository manager

%CSIZE%
46336

%ISIZE%
303104

%MD5SUM%
somefancymd5

%SHA256SUM%
somefancysha256

%PGPSIG%
somefancysig

%URL%
http://ushi.wurstcase.net/local-repo

%LICENSE%
GPL

%ARCH%
any

%BUILDDATE%
1332727351

%PACKAGER%
ushi <martin.kalcher@gmail.com>
'''

	NAME = '''
%NAME%
local-repo
'''

	def test_pkgbuild_parser(self):
		l, pkgbuild = mkstemp(prefix='local-repo-test-pkgbuild-')
		self.assertRaises(ParserError, PkgbuildParser(pkgbuild).parse)

		with open(pkgbuild, 'w') as f:
			f.write(ParserTest.PKGBUILD)

		self.assertRaises(ParserError, PkgbuildParser(pkgbuild).parse)

		with open(pkgbuild, 'w') as f:
			f.write(ParserTest.PKGBUILD + ParserTest.VERSION)

		info = {'depends': ['tar', 'pacman', 'python', 'huiii'],
		        'version': '1.6.2',
		        'makedepends': ['gettext'],
		        'name': 'local-repo'}

		self.assertEqual(info, PkgbuildParser(pkgbuild).parse())
		remove(pkgbuild)

	def test_pkginfo_parser(self):
		self.assertRaises(ParserError, PkginfoParser(ParserTest.PKGINFO).parse)

		info = {'name': 'local-repo',
		        'license': 'GPL',
		        'url': 'https://github.com/ushis/local-repo',
		        'builddate': '1332727351',
		        'version': '1.6.2-1',
		        'packager': 'ushi <martin.kalcher@gmail.com>',
		        'isize': '303104',
		        'arch': 'any',
		        'desc': 'Local repository manager'}

		self.assertEqual(info, (PkginfoParser(ParserTest.PKGINFO + ParserTest.PACK).parse()))

	def test_desc_parser(self):
		self.assertRaises(ParserError, DescParser(ParserTest.DESC).parse)

		info = {'filename': 'local-repo-1.6.2-1-any.pkg.tar.xz',
		        'name': 'local-repo',
		        'version': '1.6.2-1',
		        'desc': 'Local repository manager',
		        'csize': '46336',
		        'isize': '303104',
		        'md5sum': 'somefancymd5',
		        'sha256sum': 'somefancysha256',
		        'pgpsig': True,
		        'url': 'http://ushi.wurstcase.net/local-repo',
		        'license': 'GPL',
		        'arch': 'any',
		        'builddate': '1332727351',
		        'packager': 'ushi <martin.kalcher@gmail.com>'}

		self.assertEqual(info, DescParser(ParserTest.DESC + ParserTest.NAME).parse())


if __name__ == '__main__':
	main()
